permalink: /blog/:title/
theme: null
markdown: kramdown
kramdown:
  auto_ids: true
  auto_id_stripping: false

title: My Website

url: "https://rforrupesh.github.io"
baseurl: "/pdf"

plugins:
  - jekyll-sitemap


